#!/usr/bin/env python3
"""Plot CPU vs GPU runtimes from matrixMul CSV output."""

import argparse
import csv
from pathlib import Path
from typing import List, Optional

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot CPU, gemm, and tiled_gemm timings from CSV data"
    )
    parser.add_argument("csv", type=Path, help="Path to CSV generated by matrixMul")
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional image path (PNG/SVG). If omitted, the plot is shown interactively.",
    )
    parser.add_argument(
        "--max-cases",
        type=int,
        default=None,
        help="Limit the number of matrix sizes to plot (useful for crowded charts).",
    )
    return parser.parse_args()


def load_rows(csv_path: Path) -> List[dict]:
    with csv_path.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        return list(reader)


def build_series(rows: List[dict]):
    if not rows:
        raise ValueError("CSV is empty; run matrixMul with --csv first.")

    labels = []
    cpu = []
    gemm = []
    tiled_names = [key for key in rows[0].keys() if key.startswith("tiled_")]
    tiled_series = {name: [] for name in tiled_names}

    for row in rows:
        labels.append(f"{row['m']}x{row['k']}x{row['n']}")
        cpu.append(float(row["cpu_ms"]))
        gemm.append(float(row["gemm_ms"]))
        for name in tiled_names:
            value = row.get(name, "nan")
            tiled_series[name].append(float(value) if value else float("nan"))

    return labels, cpu, gemm, tiled_names, tiled_series


def plot(labels, cpu, gemm, tiled_names, tiled_series, output: Optional[Path]):
    def pretty_name(name: str) -> str:
        label = name.upper()
        return label.replace("_MS", "")

    metrics = ["CPU", "GEMM"] + [pretty_name(name) for name in tiled_names]
    data_series = [cpu, gemm] + [tiled_series[name] for name in tiled_names]

    num_cases = len(labels)
    num_series = len(data_series)
    x = np.arange(num_cases)
    width = 0.8 / num_series

    fig, ax = plt.subplots(figsize=(max(8, num_cases * 1.2), 6))
    for idx, series in enumerate(data_series):
        offset = (idx - (num_series - 1) / 2) * width
        ax.bar(x + offset, series, width, label=metrics[idx])

    ax.set_xlabel("Matrix sizes (MxKxN)")
    ax.set_ylabel("Time (ms, log scale)")
    ax.set_yscale("log")
    ax.set_title("CPU vs CUDA GEMM timings")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=30, ha="right")
    ax.legend()
    ax.grid(True, axis="y", linestyle="--", alpha=0.4)
    fig.tight_layout()

    if output:
        fig.savefig(output)
        print(f"Saved plot to {output}")
    else:
        plt.show()


def main():
    args = parse_args()
    rows = load_rows(args.csv)
    if args.max_cases is not None:
        rows = rows[: args.max_cases]
    labels, cpu, gemm, tiled_names, tiled_series = build_series(rows)
    plot(labels, cpu, gemm, tiled_names, tiled_series, args.output)


if __name__ == "__main__":
    main()
